apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: "default"
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - image: scdk159/f-ticket_flask_app:main
          name: flying-tickets-app

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: "default"
  labels:
    app: flask-app
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  selector:
    app: flask-app
  type: "LoadBalancer"
  loadBalancerIP: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb

  template:
    metadata:
      labels:
        app: mongodb
        
    spec:
      containers:
        - image: mongo
          name: mongodb
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-claim0
            - mountPath: /seeds
              name: mongodb-claim1
            - mountPath: /docker-entrypoint-initdb.d/mongo_script.sh
              name: mongodb-claim2

          ports:
            - containerPort: 27017
      volumes:
        - name: mongodb-claim0
          persistentVolumeClaim:
            claimName: mongodb-claim0
        - name: mongodb-claim1
          persistentVolumeClaim:
            claimName: mongodb-claim1
        - name: mongodb-claim2
          persistentVolumeClaim:
            claimName: mongodb-claim2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-claim0

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-claim1

spec:
  accessModes:
    - ReadWriteOnce
    
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-claim2

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: Service

metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  type: NodePort
  ports:
    - port: 27017
  selector:
    app: mongodb